### ISSUE TITLE
Question on naming/metadata convention for channels/playlists

### ISSUE THREAD

**Issue by cscattaglia917** [arabcoders/emby-ytdlp-info-reader-plugin#11]
I think I am following the naming conventions for files and corresponding metadata, but not sure if what I am seeing is expected behavior.  This is a "Shows" library in Emby.
Right now I have two channels. One with a single playlist containing 145 videos(Bailey Sarian - only a few videos in library while I test right now.) Another channel with a few different playlists.

One channel - Bailey Sarian - only shows up in Emby as "Murder, Mystery, and Makeup" (playlist name) even though the folder structure is like so: \media\videos\YouTube\Bailey Sarian\Murder, Mystery & Makeup\ - I was expecting to see "Bailey Sarian" on the main page, like how I see "Hoonigan" on the main page(channel with multiple playlists.)
![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/3612900/b079c801-63a3-489a-8d29-954048146c87)

I have the .info.json and .jpg for the channel in the "Channel" folder:
![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/3612900/1448c78f-8ce7-4c91-996b-5e9656cdcf7f)

And corresponding .info.json/.jpg files for each video and the playlist info/jpg in the "Murder, Mystery & Makeup" folder, yet Emby doesn't seem to display any of this metadata. 

![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/3612900/2012142d-c527-42db-b676-47392b8d3591)

I also was expecting all of the Bailey Sarian videos to be in one "Season/Folder" within Emby considering they are all part of the same playlist?  This IS how the Hoonigan media is behaving so that's another reason why I am confused.
![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/3612900/eac29e6d-0ac4-41af-ab26-91171e583442)

**Comment by arabcoders** [comment]
Hi,

As far as i know my plugins doesn't support nested playlists so try saving your playlists as a series instead of nested inside a folder i.e instead of

```
\media\videos\YouTube\channel\playlist 1 [id]
\media\videos\YouTube\channel\playlist 2 [id]
```

do

```
\media\videos\YouTube\channel - playlist 1 [id]
\media\videos\YouTube\channel - playlist 2 [id]
```

basically you either download the entire channel as non playlist or or have the playlist as series folder itself.

**Comment by cscattaglia917** [comment]
Like this? 
![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/3612900/006ad609-f1c3-48f7-98ee-f559fe876396)

That does at least solve the issue of "Bailey Sarian" not appearing on the main screen, but the single playlist is still spread out across seasons by year and doesn't pull in metadata about the channel or playlist.  It seems the channel metadata in the screenshot below is actually metadata for the last file in the playlist.

![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/3612900/19cea6ee-15ec-44e5-9bb3-78321aec81ba)

Thanks for all your help!

**Comment by arabcoders** [comment]
Hi, You are only supposed to have a playlist info at the root of series. like the following image.

![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/1621552/adb75b2b-536c-41c4-aaa2-51b99313167a)

The folders doesn't matter match inside the main directory but it's easier to navigate huge channels.

This is also from the same channel but separate playlist

![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/1621552/1fa752f2-a6f7-4225-b14a-31fe351101da)


How they look like at emby

P1
![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/1621552/619e00b0-a97a-4195-84e4-c4954d7f4ea3)

P2
![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/1621552/b5569ad3-1ca1-4156-bddf-5ed1b32b8de2)

**Comment by cscattaglia917** [comment]
Really appreciate the examples, that is super helpful and also looks like some cool videos! I am able to replicate your setup perfectly with the Elden Ring playlist so that is good and I should be able to use that as a reference. (And got some cool new videos to watch in the process!)

More of a yt-dlp question than anything.. I can't seem to get the output format to automatically create the Season based on video release year. Using the below returns Season NA. Assuming because the playlist doesn't have a year?  Do you use FileBot or something else to help you create the Seasons based on year at the filesystem level?

> -o "%(playlist)s [PLvFQJa1XAXzwyhl0pCkh_PcQDfz5nyg9L]/Season %(release_year)s/%(title)s - [(%(id)s)].%(ext)s

**Comment by cscattaglia917** [comment]
What's interesting is that I feel I am using the same structure now for Murder, Mystery & Makeup yet still seeing some metadata missing/incorrect.
![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/3612900/05214359-4e12-4bec-a1bc-e821ffe23775)

![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/3612900/5c4734ab-84ed-453d-81d8-7b4654a1e0ef)

![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/3612900/5c733ae4-bb1d-4401-8372-4b9137ba521d)


I might just be missing something small and stupid, any help is greatly appreciated!

**Comment by arabcoders** [comment]
Indeed it's something small


the id need to be like this [id] or [youtube-id] yours have () around the ID. 

`[(PLCprSpAj-wvAf619ulK_2B_4BrHJM4j1s)]` need to be `[PLCprSpAj-wvAf619ulK_2B_4BrHJM4j1s]`. 

As for naming no i use regular yt-dlp with little advanced format i will share it later i am not at PC

**Comment by cscattaglia917** [comment]
That was it! Perfect, thank you!

**Comment by arabcoders** [comment]
@cscattaglia917 so yeah i use `ytptube` as downloader and the command mostly come down to this format

```bash
$ yt-dlp --paths "home:/media/youtube/" --paths "temp:/tmp" --output '%(playlist,channel)s [%(playlist_id,channel_id,id)s]/Season %(release_date>%Y,upload_date>%Y|Unknown)s/%(release_date>%Y%m%d,upload_date>%Y%m%d)s - %(title).180B [%(extractor)s-%(id)s].%(ext)s' -- url
```
