### ISSUE TITLE
Incorrect Artist added in Metadata Field in Emby

### ISSUE THREAD

**Issue by cscattaglia917** [arabcoders/emby-ytdlp-info-reader-plugin#9]
Hi,

I am having some issues with Music Videos and incorrect artist values being populated.. I have my Library settings like this:
![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/3612900/205106eb-4682-4601-9967-a52e66f63c54)
![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/3612900/8f5e8434-77e4-49f8-a4c3-ea038b38fa74)

For some reason, every music video is populated with the artist SZA. I can not find references to this artist in the corresponding info.json files so I am not sure where this is coming from.  Any help is greatly appreciated. 

Also attaching a random info.json file for one of the affected videos. 
[[(3CxtK7-XtE0)].info.json](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/files/14270631/3CxtK7-XtE0.info.json)

And I have the emby log file as well if desired.

**Comment by arabcoders** [comment]
Hi, Thanks for your report, can you go to the item and click the edit metadata and post screenshot of the data there?

Also from quick look at the JSON file it seems the file is classified as normal video which lacks the `artist/album` property, and emby seems to be randomly using this SZA as default value back.

**Comment by cscattaglia917** [comment]
Sure can, thanks for your hard work!

![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/3612900/5ff04e09-f4e2-4a30-b679-acd03eab2c07)
![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/3612900/02daaaf5-2f34-40dc-8e23-519df3627541)
![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/3612900/8cf584ea-0419-4ee1-8997-4f7f15edea37)
![image](https://github.com/arabcoders/emby-ytdlp-info-reader-plugin/assets/3612900/bcc6a31b-0785-4173-a334-43e935e19866)

**Comment by arabcoders** [comment]
Thanks, it seems i have to add fallback to artist field incase it's not available to use the channel name.

No worries.

**Comment by cscattaglia917** [comment]
I think that should work well for most cases.

**Comment by arabcoders** [comment]
@cscattaglia917 please download `v1.1.0.3` and see if it fixes your problem and report back pls

**Comment by cscattaglia917** [comment]
Looks good and works well for most cases! The cases where it doesn't work are more of an issue with the uploader being named something that doesn't match the artist name, so thank you!

**Comment by arabcoders** [comment]
> Looks good and works well for most cases! The cases where it doesn't work are more of an issue with the uploader being named something that doesn't match the artist name, so thank you!

You can manually edit the channel name in `.info.json` file to something suitable, The fallback is as i described if `artist` property is found it will use that, if not it will fallback to `channel` property which should always exists.

Sadly, the only other workaround i can think of is you can alter the `channel` or add `artist` field into the `.info.json` file and it should be reflected in your emby/jf.

Happy watching.

**Comment by cscattaglia917** [comment]
Oh interesting, I didn't know that .info.json had an artist property ever(I have not seen one personally.) Good to know! Thank you!

**Comment by arabcoders** [comment]
> Oh interesting, I didn't know that .info.json had an artist property ever(I have not seen one personally.) Good to know! Thank you!

youtube-dl used to have them and i assume yt-dlp does too along side `album` and `track` properties. Not sure on what logic they add the fields though.
